DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS COURS;
DROP TABLE IF EXISTS MEMBRE;
DROP TABLE IF EXISTS TARIF;
DROP TABLE IF EXISTS PONEY;

DROP TRIGGER IF EXISTS poidsInfPoidsMax;
DROP TRIGGER IF EXISTS nbParticipantsMaxAtteint;
DROP TRIGGER IF EXISTS cotisationPayee;
DROP TRIGGER IF EXISTS coursParticulier;
DROP TRIGGER IF EXISTS checkReposPoney;
DROP TRIGGER IF EXISTS checkChevauchementReservation;
DROP TRIGGER IF EXISTS checkDispoMoniteur;


