-- Generated by Mocodo 4.2.11

CREATE TABLE COURS (
  PRIMARY KEY (cours_ID),
  cours_ID            INT(4) NOT NULL,
  type_C              ENUM('Collectif', 'Particulier'),
  duree               INT(1) CHECK (duree IN (1, 2)),
  nb_Participants_Max INT(4) DEFAULT 10 CHECK (nbParticipantsMax <= 10),
  jour                ENUM('Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'),
  heure_D             TIME,
  heure_F             TIME DEFAULT ADDTIME(heureD, duree * 10000),
  prix                DECIMAL(10,2),
  id_M                INT(4) NOT NULL
);

CREATE TABLE MEMBRE (
  PRIMARY KEY (id_M),
  id_M             INT(4) NOT NULL,
  nom_M            VARCHAR(42),
  prenom_M         VARCHAR(42),
  date_Naissance   DATE,
  email            VARCHAR(42) UNIQUE,
  mot_De_Passe     VARCHAR(100),
  telephone        VARCHAR(42),
  poids_A          DECIMAL(10,2) NULL,
  niveau           VARCHAR NULL,
  id_T             INT(4) NULL,
  cotisation_Annee INT NULL,
  payee_Cotisation BOOLEAN NULL,
  annee_Experience INT(2) NULL
);

CREATE TABLE PONEY (
  PRIMARY KEY (poney_ID),
  poney_ID              INT(4) NOT NULL,
  nom_P                 VARCHAR(42),
  age                   INT(4),
  poids_Supportable_Max DECIMAL(10,2)
);

CREATE TABLE RESERVATION (
  PRIMARY KEY (id_M, poney_ID, cours_ID),
  id_M        INT(4) NOT NULL,
  poney_ID    INT(4) NOT NULL,
  cours_ID    INT(4) NOT NULL,
  cours_Payee BOOLEAN
);

CREATE TABLE TARIF (
  PRIMARY KEY (id_T),
  id_T       INT(4) NOT NULL,
  descriptif VARCHAR(42),
  montant    DECIMAL(10,2)
);

ALTER TABLE COURS ADD FOREIGN KEY (id_M) REFERENCES MEMBRE (id_M);

ALTER TABLE MEMBRE ADD FOREIGN KEY (id_T) REFERENCES TARIF (id_T);

ALTER TABLE RESERVATION ADD FOREIGN KEY (cours_ID) REFERENCES COURS (cours_ID);
ALTER TABLE RESERVATION ADD FOREIGN KEY (poney_ID) REFERENCES PONEY (poney_ID);
ALTER TABLE RESERVATION ADD FOREIGN KEY (id_M) REFERENCES MEMBRE (id_M);
